### ISSUE TITLE
Merge upstream: deprecated API

### ISSUE THREAD

**Issue by ishitatsuyuki** [omnirom/android_hardware_samsung_slsi_exynos5#1]
error: 'getdtablesize' was not declared in this scope
This API is deprecated in POSIX (and android of course), so pull upstream changes is needed to solve this compile error.

**Comment by Entropy512** [comment]
We do not accept pull requests on github.  Please submit changes through gerrit.omnirom.org, or if things are too significant to go through Gerrit, talk to a member of the team on IRC (#omni in irc.freenode.net - warning, we idle for extended periods of time using bouncers)
